### ISSUE TITLE
Sleek and App

### ISSUE THREAD

**Issue by oCuRL** [tlhunter/sleekmvc#2]
When uploading, sleek and the sleep app, I'm getting errors straight away, before i even do anything once it's uploaded.

Here are the error(s):

Fatal error: Uncaught exception 'Sleek\Exception_ClassNotFound' with message 'App\Controller_' in /home/oCuRL/public_html/system/Autoload.php:44 Stack trace: #0 [internal function]: Sleek\Autoload::loader('App\Controller_') #1 /home/oCuRL/public_html/system/Error.php(23): spl_autoload_call('App\Controller_') #2 /home/oCuRL/public_html/system/Config.php(25): Sleek\Error::handler(8, 'Undefined index...', '/home/oCuRL/...', 25, Array) #3 /home/oCuRL/public_html/system/Config.php(42): Sleek\Config::load() #4 /home/oCuRL/public_html/system/Request.php(26): Sleek\Config::get('default_control...') #5 /home/oCuRL/public_html/system/Request.php(50): Sleek\Request->__construct() #6 /home/oCuRL/public_html/system/Core.php(33): Sleek\Request::getInstance() #7 /home/oCuRL/public_html/index.php(32): Sleek\Core->__construct() #8 {main} thrown in /home/oCuRL/public_html/system/Autoload.php on line 44

**Comment by tlhunter** [comment]
Did you download the sample application as well as the framework and put
them in the right directories?

**Comment by oCuRL** [comment]
Yes i done that, and i get that error.
Downloaded the app, uploaded that to my server, then downloaded the system and put them in the system folder.
I done it a few times to make sure i was doing it correctly, and i'm getting the error still, thanks.

**Comment by tlhunter** [comment]
Can you tell me what version of PHP you have?

```
php -v
```

It looks like this is a linux server.
Is it a shared host?
Is it running Apache?
Is the .htaccess file in the root of the server (it's hidden btw)?

**Comment by oCuRL** [comment]
It's running on one of my shared hosts running 5.3. something, runs apache yes, also .htaccess is there too.

I've also tryed running on a few servers i currectly run, tryed running it on two dedicated boxes, 3 vps servers, and then i tryed shared hosting, Still nothing.

**Comment by tlhunter** [comment]
Definitely sounds like a bug to me. I'll look into it.

**Comment by oCuRL** [comment]
Sorry! Very sorry! I got this working in the end, i done a complete new setup on a new box, configured apache and php myself, instead of getting my host todo it. I got it working out of the box, though did have to adjust the .htaccess file as i put it into a different folder. Maybe you should add it to the .htaccess file it's self here, and edit the documents for it? I had to add "RewriteBase /~sleekmvc/" into the .htaccess file for myself. I'd also love to see you add the routing system when you have time. So i can get rid of them rewrites in the .htaccess file, hehe :P. I might give it a go myself if i have enough time on my hands. Thanks for sleekmvc, hope to see routing system. :)
